### ISSUE TITLE
download

### ISSUE THREAD

**Issue by pro100mir** [dreamRs/billboarder#12]
How can someone download a chart as a png/jpeg?

**Comment by pro100mir** [comment]
Dear Victor,

Thank you for this. It works when running your example, good job!

When updating in my project the package to this development version, it makes all billboarded charts no longer to appear. It works well before with 0.2.7. Any idea why is this happening? 

Thank you,
Mircea

**Comment by pvictor** [comment]
Hello, 
It's possible I broke everything... I made a lot of changes.
Can you re-install from GitHub and retry ? Last version is `0.2.7.940`.
Otherwise can you provide an example where it don't work anymore ?
Or show me if there's errors in the JavaScript console ? (right click + inspect element + console in your browser)

Sorry for the inconvenience.

Victor

**Comment by pro100mir** [comment]
Hi Victor

I am attaching a copy paste from console. I notice that when I run a particular chart on the console, it works, however in shiny is not showing the graphs.

Thank you,
Mircea

**Comment by pro100mir** [comment]
Hi Victor

Attaching also a print screen from browser (safari) javascript console.

Let me know if I can provide more details.

Thank you,
Mircea

**Comment by pvictor** [comment]
Hi Mircea,

I can't see any attachments when you reply by email, can you add those directly in the issue thread (https://github.com/dreamRs/billboarder/issues/12) ? Or send them by email at <victor.perrier at dreamrs.fr> ?

Thanks

**Comment by pvictor** [comment]
Hi Mircea, are you using Internet Explorer ?

**Comment by pvictor** [comment]
Can you install the dev version and see if it's better ? 
To install dev version : 
```r
devtools::install_github("dreamRs/billboarder")
```
