### ISSUE TITLE
shinymanager logs graphics not showing 

### ISSUE THREAD

**Issue by bthieurmel** [dreamRs/billboarder#26]
Due to billboarder JS error. Only with "0.3.0"

So I think it's a ``billboarder`` issue``...!

**Comment by pvictor** [comment]
Oups, I'll fix that

**Comment by pvictor** [comment]
This is caused by the `max` argument here : https://github.com/datastorm-open/shinymanager/blob/af19454ce8ef8393b05ef73eec2e22a592b41949/R/modules-logs.R#L228

Removing `, max = max(nb_log_day$day) + 1` will fix the issue

Otherwise this is fixed in `billboard.js` here : https://github.com/naver/billboard.js/issues/1981
I wait for the next release and I will upgrade `billboarder` on CRAN.

**Comment by bthieurmel** [comment]
Ok. Thanks. I've just remove ``max = max(nb_log_day$day) + 1`` in ``shinymanager``
